# default_index:
#    path: /
#    controller: App\Controller\DefaultController::index

# default_getplateform:
#    path: /plateform
#    controller: App\Controller\DefaultController::getplateform

# annonces_listall:
#    path: /annonces
#    controller: App\Controller\AnnoncesController::listall

# annonces_detail:
#    path: /annonces/{id}
#    controller: App\Controller\AnnoncesController::detail

# annonces_add:
#    path: /annonces/list/add
#    controller: App\Controller\AnnoncesController::add

